import React, { useState } from "react";
import axios from "axios";
import { useAppStore } from "../store/useAppStore";

export default function JoinSession() {
  const [pin, setPin] = useState("");
  const [loading, setLoading] = useState(false);
  const { setRoomId, initializeWebSocket } = useAppStore();

  const handleJoin = async (e) => {
    e.preventDefault();
    if (pin.length < 7) {
      alert("Please enter a valid 7-digit PIN.");
      return;
    }

    setLoading(true);
    try {
      const backendHost =
        window.location.hostname === "localhost"
          ? "localhost:8000"
          : `${window.location.hostname}:8000`;

      // Verify room exists
      await axios.get(`http://${backendHost}/api/v1/rooms/${pin}`);

      setRoomId(pin);
      initializeWebSocket(pin);
    } catch (err) {
      alert("Invalid Room PIN or room has expired.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white p-6 rounded-2xl shadow-md max-w-md w-full">
      <h2 className="text-2xl font-bold mb-4 text-gray-800 text-center">
        Join Session
      </h2>
      <p className="text-gray-600 mb-6 text-sm text-center">
        Enter the 7-digit PIN generated by the hosting machine to connect.
      </p>
      <form onSubmit={handleJoin} className="space-y-4">
        <input
          type="text"
          maxLength={7}
          placeholder="Enter 7-Digit Room PIN"
          value={pin}
          onChange={(e) => setPin(e.target.value.replace(/\D/g, ""))}
          className="w-full px-4 py-3 border border-gray-300 rounded-xl text-center text-lg tracking-widest focus:outline-none focus:border-blue-500"
        />
        <button
          type="submit"
          disabled={loading || pin.length < 7}
          className="w-full bg-emerald-600 hover:bg-emerald-700 text-white font-semibold py-3 px-4 rounded-xl transition duration-200 disabled:opacity-50"
        >
          {loading ? "Connecting..." : "Join Session"}
        </button>
      </form>
    </div>
  );
}
